# Splitwise Setup Codes
splitwise:
  consumer_key: '8LbJU3xKBdSz5O6GKlz2OAwTMgIkJIRO3sGzJ1kG'
  consumer_secret: 'wYjZ0AFOV88aJqglyLqZRsSb5afWEcfHJ2HOK5f6'

# YNAB Setup Codes
ynab:
  client_id: 'CExJQI46Zsr1FSIU90MCcRh60y27CQmh1mLEizSyJOc'
  client_secret: 'TQxp-ikd2pVDT-SMc3_pOteMTi-q7037hv9Gx75CeQQ'
  budget_id: '29868c31-b3f0-4e03-8d8f-e3da8bda16c3'
  account_id: '45df6016-0a4f-43ea-8b87-f2ad63b817ef'
